# Generated by Django 4.0.4 on 2022-04-20 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('home_type', models.CharField(max_length=50)),
                ('amenities', models.CharField(max_length=700)),
                ('image', models.CharField(max_length=300)),
                ('contact_name', models.CharField(max_length=200)),
                ('contact_email', models.CharField(max_length=254)),
                ('bedrooms', models.CharField(max_length=200)),
                ('available', models.BooleanField()),
            ],
            options={
                'ordering': ['location'],
            },
        ),
    ]
