# Generated by Django 4.0.4 on 2022-04-20 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_home_bathrooms_home_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='price',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
