# Generated by Django 4.0.4 on 2022-04-20 05:31

import django.core.validators
from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_home_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField(default=2022, validators=[django.core.validators.MinValueValidator(1984), main_app.models.max_value_current_year])),
                ('image', models.CharField(max_length=300)),
                ('color', models.CharField(max_length=100)),
                ('car_type', models.CharField(choices=[('Minivans', 'Minivans'), ('Van', 'Van'), ('Trucks', 'Trucks'), ('Hatchback', 'Hatchback'), ('Convertible', 'Convertible'), ('SUVs', 'SUVs'), ('Coupes', 'Coupes'), ('Sedan', 'Sedan'), ('Crossovers', 'Crossovers')], max_length=100)),
                ('available', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='home',
            name='available',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], max_length=100),
        ),
        migrations.AddField(
            model_name='home',
            name='car',
            field=models.ManyToManyField(to='main_app.car'),
        ),
    ]
