# Generated by Django 4.0.4 on 2022-04-21 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_car_alter_home_available_home_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_contact_email',
            field=models.CharField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='car_contact_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.CharField(choices=[('Hatchback', 'Hatchback'), ('Trucks', 'Trucks'), ('Convertible', 'Convertible'), ('Crossovers', 'Crossovers'), ('Coupes', 'Coupes'), ('Sedan', 'Sedan'), ('SUVs', 'SUVs'), ('Van', 'Van'), ('Minivans', 'Minivans')], max_length=100),
        ),
    ]
