# Generated by Django 4.0.4 on 2022-04-21 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_car_car_contact_email_car_car_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_price',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('Hatchback', 'Hatchback'), ('Crossovers', 'Crossovers'), ('Coupes', 'Coupes'), ('Convertible', 'Convertible'), ('Minivans', 'Minivans'), ('Van', 'Van'), ('Trucks', 'Trucks'), ('SUVs', 'SUVs')], max_length=100),
        ),
    ]
