# Generated by Django 4.0.4 on 2022-04-21 03:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_car_car_price_alter_car_car_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.CharField(choices=[('Van', 'Van'), ('Coupes', 'Coupes'), ('SUVs', 'SUVs'), ('Hatchback', 'Hatchback'), ('Minivans', 'Minivans'), ('Sedan', 'Sedan'), ('Crossovers', 'Crossovers'), ('Trucks', 'Trucks'), ('Convertible', 'Convertible')], max_length=100),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_content', models.CharField(max_length=100)),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main_app.home')),
            ],
        ),
    ]
